# Generated by Django 2.1.5 on 2019-02-08 07:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('category', '0003_auto_20190208_1614'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_type', models.CharField(choices=[('Buy', '구매글'), ('Sell', '판매글')], default='Buy', max_length=10)),
                ('title', models.CharField(max_length=30)),
                ('content', models.TextField()),
                ('price', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Account')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.RemoveField(
            model_name='purchasepost',
            name='author',
        ),
        migrations.RemoveField(
            model_name='purchasepost',
            name='sub_theme',
        ),
        migrations.RemoveField(
            model_name='sellpost',
            name='author',
        ),
        migrations.RemoveField(
            model_name='sellpost',
            name='sub_theme',
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
        migrations.DeleteModel(
            name='PurchasePost',
        ),
        migrations.DeleteModel(
            name='SellPost',
        ),
    ]
