# Generated by Django 2.1.5 on 2019-02-08 17:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0004_auto_20190208_1635'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='sub_theme',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='post_sub_theme', to='category.SubTheme'),
        ),
    ]
