# Generated by Django 2.1.5 on 2019-02-15 07:57

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('category', '0007_post_apply_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='apply_user',
        ),
        migrations.AddField(
            model_name='post',
            name='apply_user',
            field=models.ManyToManyField(blank=True, related_name='applied_post', to=settings.AUTH_USER_MODEL),
        ),
    ]
