# Generated by Django 2.1.5 on 2019-02-16 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0009_post_post_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='thumbnail',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
