# Generated by Django 2.1.5 on 2019-02-16 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0011_auto_20190216_1815'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='thumbnail',
            field=models.ImageField(default='static/img/default.jpg', upload_to='thumbnail/%Y/%m/%d'),
        ),
    ]
