# Generated by Django 2.1.5 on 2019-01-20 16:32

from django.db import migrations
import django_summernote.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_summernote'),
    ]

    operations = [
        migrations.AlterField(
            model_name='summernote',
            name='summer_field',
            field=django_summernote.fields.SummernoteTextField(),
        ),
    ]
