# Generated by Django 2.1.5 on 2019-01-20 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20190121_0132'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='summernote',
            name='attachment_ptr',
        ),
        migrations.DeleteModel(
            name='SummerNote',
        ),
    ]
